stages:
  - test
  - docs
  - lint

test:
  stage: test
  image: python:3.11
  script:
    - python --version
    - python -m compileall .

docs:
  stage: docs
  image: python:3.11
  script:
    - pip install mkdocs mkdocs-material
    - mkdocs build --strict
  artifacts:
    paths:
      - site/
    expire_in: 1 week
lint:
  stage: lint
  image: python:3.11
  script:
    - cd backend
    - pip install -r requirements.txt
    - pip install pylint pylint-django
    - pylint editor config
    - pylint editor config --fail-under=7.0

