from django.urls import path
from . import views

urlpatterns = [
    path("", views.start_page, name="start"),
    path("kontakt/", views.kontakt_view, name="kontakt"),
    path("level/", views.level_view, name="level"),
    path("upload-json/", views.upload_json_view, name="upload_json"),
    path("components/", views.component_test_view, name="component_test"),
    path("createLevel/", views.create_level, name="create_level"),
    path("auswahl/", views.auswahl_view, name="auswahl_view"),
    path("createLevel1/", views.create_level1_view, name="create_level1"),
    path("createLevel2/", views.create_level2_view, name="create_level2"),
    path("createLevel21/", views.create_level21_view, name="create_level21"),
    path("createLevel3/", views.create_level3_view, name="create_level3"),
    path("createLevel3-1/", views.create_level31_view, name="create_level31"),
    path("createLevel3table/", views.create_level3table_view, name="create_level3table"),
    path("createLevel3hint/", views.create_level3hint_view, name="create_level3hint"),
    path("createLevel3exit/", views.create_level3exit_view, name="create_level3exit"),
    path("createLevel4/", views.create_level4_view, name="create_level4"),
    path("createLevel5/", views.create_level5_view, name="create_level5"),
    path("createLevel51/", views.create_level51_view, name="create_level51"),
    path("createLevel6/", views.create_level6_view, name="create_level6"),
    path("createLevel6-1/", views.create_level61_view, name="create_level61"),
    path("createLevel6-2/", views.create_level62_view, name="create_level62"),
    path("createLevel7/", views.create_level7_view, name="create_level7"),
    path("createLevel8/", views.create_level8_view, name="create_level8"),
    path("export-game/", views.export_game_view, name="export_game"),
    path("levelGrunddaten/", views.level_grunddaten_view, name="levelGrunddaten"),
    path("sqlGrunddaten/",views.sql_grunddaten_view, name="sql_grunddaten_view"),
    path("gegenstandVerwaltung/", views.gegenstand_view, name="gegenstandVerwaltung"),
    path("gegenstandVerwaltung/<str:item_id>/bearbeiten/",views.edit_item_view,name="edit_item"),
    path("gegenstandVerwaltung/<str:item_id>/bearbeiten/<str:section>/",views.edit_item_section_view,name="edit_item_section"),
    path("gegenstandVerwaltung/<str:item_id>/entfernen/",views.delete_item_view,name="delete_item"),
    path("messagesGrunddaten/",views.messages_grunddaten_view,name="messages_grunddaten"),
    path("level/<str:level_id>/bearbeiten/",views.edit_level_view,name="edit_level"),
    path("level/speichern/",views.save_level_view,name="save_level"),
    path("level/<str:level_id>/delete/",views.delete_level_view,name="delete_level"),
]
